name: Backend CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t christopherpallo2000/cp-read-product-service .
      - name: Publish image to docker hub
        run: docker push christopherpallo2000/cp-read-product-service:latest   

  deploy: 
    needs: build
    runs-on: product-read    
    steps:
      - name: Pull image from docker hub
        run: docker pull christopherpallo2000/cp-read-product-service:latest
      - name: Delete Old Container
        run: docker rm -f readproductService || true
      - name: Run docker container
        run: docker run -d --name readproductService -p 8091:8091 christopherpallo2000/cp-read-product-service